services:
    nginx:
        image: nginx:alpine
        container_name: notepad-nginx
        restart: unless-stopped
        ports:
            - "8088:80"
        volumes:
            - ./:/var/www
            - ./docker/php/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - notepad
        depends_on:
            - php_fpm

    php_fpm:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: notepad-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - notepad
        depends_on:
            - mysql
            - postgres

    mysql:
        image: mysql:8.0
        container_name: notepad-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: notepad
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: password
            MYSQL_USER: notepad
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
        networks:
            - notepad
        ports:
            - "3366:3306"

    postgres:
        image: postgres:15
        container_name: notepad-postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: notepad
            POSTGRES_USER: notepad
            POSTGRES_PASSWORD: password
        volumes:
            - ./docker/postgres:/docker-entrypoint-initdb.d
        networks:
            - notepad
        ports:
            - "5433:5432"

networks:
    notepad:
        driver: bridge
